rm(list=ls());
setwd("/home/amann/R/UCI HAR Dataset");  #Setting the working directory  where data is located


#Reading the data 
activityType<-read.table("activity_labels.txt");
features<-read.table("features.txt");
#Reading the training dataset
subjectTrain<-read.table("./train/subject_train.txt");
xTrain<-read.table("./train/X_train.txt");
yTrain<-read.table("./train/y_train.txt");

#Reading the test dataset
subjectTest<-read.table("./test/subject_test.txt");
xTest<-read.table("./test/X_test.txt");
yTest <- read.table("./test/y_test.txt");

#Setting the column names of the read data to a meaningful one
colnames(activityType)<-c("activityID","activity");
colnames(features) <- c("featuresID","feature");

#setting the column names of the training data
colnames(xTrain)<-features[,2];
colnames(yTrain)<-c("activity");
colnames(subjectTrain)<-c("subjectID");

#Getting the training data by merging all the test data that was read
trainingData<-cbind(subjectTrain,yTrain,xTrain);

#Setting the column names of the test data
colnames(xTest)<-features[,2];
colnames(yTest)<-c("activity");
colnames(subjectTest)<-c("subjectID");

#Getting the test data by merging all the test data that was read
testData<-cbind(subjectTest,yTest,xTest);

#By merging the test data and train data we get the final data
finalData<-rbind(trainingData,testData);

#column names of the finalData is stored in a vector colnames
colnames<-names(finalData);

#selecting all the column containing mean() and std() pattern existing in the last part of name
colvector<-c(1,2,grep("-mean..$",colnames),grep("-std..$",colnames));

#subsetting the data based on the above colvector variable
finalData<-finalData[,colvector];

#Getting the column names of the data from the subset data
colnames<-names(finalData);

#Giving the column names of the finalData a descriptive name
for(i in 1:length(colnames)){
  colnames[i]=gsub("\\()","",colnames[i]);
  colnames[i]=gsub("^t","time",colnames[i]);
  colnames[i]=gsub("^f","freq",colnames[i]);
  colnames[i]=gsub("-mean","Mean",colnames[i]);
  colnames[i]=gsub("-std","StdDev",colnames[i]);
  colnames[i]=gsub("[Gg]ravity","Gravity",colnames[i]);
  colnames[i]=gsub("BodyBody","Body",colnames[i]);
  colnames[i]=gsub("Mag","Magnitude",colnames[i]);
}

#Asssign the descriptive name to the finalData again
names(finalData)<-colnames;

#Tidy data is generated by subsetting the data with activity, subjectID and the mean for each variable
tidydata<-aggregate(finalData,by=list(finalData$activity,finalData$subjectID),FUN="mean");

#Tidy data contains same two rows repeated. Removing the duplicate two rows from the data
tidydata<-tidydata[,3:ncol(tidydata)];

#Tidydataset is written to a text file
write.table(tidydata,"./tidydata1.txt",row.names=FALSE,sep='\t');

